### ISSUE TITLE
Audio Player is not playing from stream on iOS after recording, and player.IsPlaying is always false

### ISSUE THREAD

**Issue by dipenbhavsar9** [jfversluis/Plugin.Maui.Audio#104]
Hi team,
I am using this plugin for recording and playing sound.
When i click play button to play sound that time i am adding 
[WP_Recorder (2).zip](https://github.com/jfversluis/Plugin.Maui.Audio/files/14649372/WP_Recorder.2.zip)

You can check RecordAudio.xaml view which is to Record and Play Audio. 

Here when Play duration ends after that PlaybackEnded event is not working and is not called. Everything works very well for android.
iOS having issue to play sound etc.

**Comment by bijington** [comment]
I'm hopeful this is fixed by https://github.com/jfversluis/Plugin.Maui.Audio/pull/101

**Comment by dipenbhavsar9** [comment]
Hi @bijington 
I am using latest version of the plugin but its not fixed and having the issue.
Please review my code and i have worked on RecordSound.Xaml for the feature and i have attached my project for the same.

Thanks for your quick reply.
Regards,
Dipen

**Comment by bijington** [comment]
The PR that I linked to hasn't been merged yet so it isn't in the latest release. If you check the PR you will see it links to 3 other issues that all appear to be the same as yours. Hopefully we can get it merged soon and then released

**Comment by dipenbhavsar9** [comment]
That sounds great,
Thanks for the support..

**Comment by dipenbhavsar9** [comment]
Hi @bijington 
Is there any chance to know when will be the new release available?

**Comment by bijington** [comment]
I can't make any guarantees when it will be ready, the current remaining tasks are to review and test the changes. If you are keen to see this released would you be able to clone the repo and test the changes against your use case?

**Comment by dipenbhavsar9** [comment]
Hi @bijington ,
Thanks for making trust on me, Yes i can do test with the release by cloning the repo.

**Comment by dipenbhavsar9** [comment]
Hi @bijington ,
Can I get dlls by platforms so I can test on my side and provide you confirmation?

Or how do I test please let me know.

Thanks

**Comment by dipenbhavsar9** [comment]
Hi @bijington ,
Can I get dlls by platforms so I can test on my side and provide you confirmation?

Or how do I test please let me know.

Thanks

**Comment by jfversluis** [comment]
Hey @dipenbhavsar9!

Thanks for your interest here! I setup a private NuGet feed for packages that are now generated for each PR so you can test things out more easily.

You can follow the instructions [here](https://learn.microsoft.com/azure/devops/artifacts/nuget/consume?view=azure-devops&tabs=windows) to add a new NuGet feed to your Visual Studio, the feed to use is: https://jfversluis.visualstudio.com/Plugin.Maui.Audio/_artifacts/feed/Plugin.Maui.Audio

The version that you are looking for is: 3.0.0-preview2.83614850791

Note that these versions do not represent (upcoming) releases so while it's great to test things out, make sure you don't use it in production, things might break later.

Let me know if that works for you!

**Comment by dipenbhavsar9** [comment]
Hi @jfversluis ,
Thanks for sending me nuget link, I am not getting that package by the link and i am getting error below..

[MauiAudio] An error occurred while parsing EntityName. Line 19, position 247.

Thanks

**Comment by jfversluis** [comment]
My bad, I added the wrong link for the NuGet feed, added the right one now above!

**Comment by dipenbhavsar9** [comment]
Thankyou @jfversluis 
You made my day, everything worked very well and all my issues fixed with that preview version.

Player.IsPlaying() and audioPlayer.Play(_stream)l both worked for iOS same like Android.

Thanks..

**Comment by jfversluis** [comment]
Great, thanks for letting us know! We'll review the PR and hopefully merge it soon for an official release!
